services:
  eden-miner1:
    build: .
    ports:
      - "10001:10001"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=1
    command: 
      - python 
      - -m 
      - eden_subnet.miner.eden 
      - --key_name
      - eden.Miner_1
      - --host
      - "0.0.0.0"
      - --port
      - "10001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]