services:
  CONTAINER_NAME:
    build: .
    ports:
      - "PORT:PORT"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=CUDA_DEVICE
    command: 
      - python 
      - -m 
      - MODULE_PATH
      - --key_name
      - KEY_NAME
      - --host
      - "HOST"
      - --port
      - "PORT"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
