services:
  eden-validator0:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=3
    command: 
      - python 
      - -m 
      - eden_subnet.validator.eden
      - --key_name
      - eden.Validator_0
      - --host
      - "0.0.0.0"
      - --port
      - "10000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  eden-validator1:
    build: .
    ports:
      - "10010:10010"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=1
    command: 
      - python 
      - -m 
      - eden_subnet.validator.eden 
      - --key_name
      - eden.Validator_1
      - --host
      - "0.0.0.0"
      - --port
      - "10010"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  eden-validator2:
    build: .
    ports:
      - "10020:10020"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=2
    command: 
      - python 
      - -m 
      - eden_subnet.validator.eden 
      - --key_name
      - eden.Validator_2
      - --host
      - "0.0.0.0"
      - --port
      - "10020"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]