services:
  yikes-miner-1:
    build: .
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=$GPU_INDEX
    command:
      - python
      - -m
      - eden_subnet.miner.$FILENAME
      - --key_name
      - $FILENAME.$CLASSNAME
      - --host
      - $HOST
      - --port
      - $PORT
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  eden-miner2:
    build: .
    ports:
      - "10002:10002"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=2
    command:
      - python
      - -m
      - eden_subnet.miner.eden
      - --key_name
      - eden.Miner_2
      - --host
      - "0.0.0.0"
      - --port
      - "10002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  eden-miner3:
    build: .
    ports:
      - "10003:10003"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=3
    command:
      - python
      - -m
      - eden_subnet.miner.eden
      - --key_name
      - eden.Miner_3
      - --host
      - "0.0.0.0"
      - --port
      - "10003"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  eden-miner4:
    build: .
    ports:
      - "10004:10004"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command:
      - python
      - -m
      - eden_subnet.miner.eden
      - --key_name
      - eden.Miner_4
      - --host
      - "0.0.0.0"
      - --port
      - "10004"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  eden-miner5:
    build: .
    ports:
      - "10005:10005"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=1
    command:
      - python
      - -m
      - eden_subnet.miner.eden
      - --key_name
      - eden.Miner_5
      - --host
      - "0.0.0.0"
      - --port
      - "10005"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  eden-miner6:
    build: .
    ports:
      - "10006:10006"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=2
    command:
      - python
      - -m
      - eden_subnet.miner.eden
      - --key_name
      - eden.Miner_6
      - --host
      - "0.0.0.0"
      - --port
      - "10006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  eden-miner7:
    build: .
    ports:
      - "10007:10007"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=7
    command:
      - python
      - -m
      - eden_subnet.miner.eden
      - --key_name
      - eden.Miner_7
      - --host
      - "0.0.0.0"
      - --port
      - "10007"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
  eden-miner8:
    build: .
    ports:
      - "10008:10008"
    volumes:
      - .:/code
      - /home/ubuntu/.commune:/root/.commune
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=3
    command:
      - python
      - -m
      - eden_subnet.miner.eden
      - --key_name
      - eden.Miner_8
      - --host
      - "0.0.0.0"
      - --port
      - "10008"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
